# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pikurr
                                 A QGIS plugin
 отображение данных pikurr
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-18
        git sha              : $Format:%H$
        copyright            : (C) 2024 by ss
        email                : xx@yy.zz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .pikurr_dialog import pikurrDialog
import os.path


class pikurr:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'trash_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&pikurr')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('pikurr', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/trash/icon_2.png'
        self.add_action(
            icon_path,
            text=self.tr(u'pikurr'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&pikurr'),
                action)
            self.iface.removeToolBarIcon(action)
    


    def run(self):
        """Run method that performs all the real work"""
        import platform, requests 
        from requests.exceptions import RequestException        
        def check_service_availability(url, timeout=5):
            """Проверяет доступность GeoServer по URL."""
            try:
                # Проверяем доступность стандартного endpoint GeoServer
                response = requests.get(f'{url}/geoserver', timeout=timeout)
                return response.status_code == 200
            except RequestException:
                return False
        
        def get_geoserver_url():
            """Возвращает рабочий URL GeoServer."""
            primary_url = "http://localhost:8080"
            #secondary_url = "http://158.160.183.235:8080"
            secondary_url = "http://geobotany.xyz"
            
            if check_service_availability(primary_url):
                print("Локальный GeoServer доступен, используем localhost")
                return primary_url
            elif check_service_availability(secondary_url):
                print("Локальный GeoServer недоступен, используем альтернативный сервер")
                return secondary_url
            else:
                raise Exception("Оба сервера GeoServer недоступны")
                from qgis.PyQt.QtWidgets import QMessageBox
                QMessageBox.critical(None, 'Error', f'geoserver is not available')
                return
             
        
        self.geoserver_url = get_geoserver_url()        
         
                
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = pikurrDialog()
        self.dlg.esriButton.toggled.connect(self.base_map)
        self.dlg.baseButton.toggled.connect(self.base_map)
        self.dlg.osmButton.toggled.connect(self.base_map)

        xml='''<?xml version="1.0" encoding="UTF-8"?><wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
                <ows:Identifier>gs:Query</ows:Identifier>
                <wps:DataInputs>
                    <wps:Input>
                    <ows:Identifier>features</ows:Identifier>
                    <wps:Reference mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST">
                        <wps:Body>
                        <wfs:GetFeature service="WFS" version="1.0.0" outputFormat="GML2" xmlns:pikurr="http://pikurr">
                            <wfs:Query typeName="pikurr:levelsagg"/>
                        </wfs:GetFeature>
                        </wps:Body>
                    </wps:Reference>
                    </wps:Input>
                    <wps:Input>
                        <ows:Identifier>attribute</ows:Identifier>
                        <wps:Data>
                            <wps:LiteralData>rn</wps:LiteralData>		
                        </wps:Data>	  
                        </wps:Input>    
                        <wps:Input>
                        <ows:Identifier>attribute</ows:Identifier>      
                        <wps:Data>        
                            <wps:LiteralData>usname</wps:LiteralData>
                        </wps:Data>
                        </wps:Input>
                        <wps:Input>
                        <ows:Identifier>attribute</ows:Identifier>      
                        <wps:Data>        
                            <wps:LiteralData>usern_co</wps:LiteralData>
                        </wps:Data>
                        </wps:Input> 
                </wps:DataInputs>
                <wps:ResponseForm>
                    <wps:RawDataOutput mimeType="application/json">
                    <ows:Identifier>result</ows:Identifier>
                    </wps:RawDataOutput>
                </wps:ResponseForm>
                </wps:Execute>'''
        import requests
        import json
        r=requests.post(f'{self.geoserver_url}/geoserver/wps',data=xml)
        self.j=json.loads(r.text)
        
        # plain and reverse dictionaries for districts and their SOATO codes
        distr={'2208':'Браславский', '2210':'Верхнедвинский', '2215':'Глубокский', '2221':'Докшицкий', '2227':'Лепельский', 
            '2233':'Миорский', '2238':'Полоцкий', '2240':'Поставский', '2242':'Россонский', '2249':'Ушачский', '2251':'Чашникский', 
            '2255':'Шарковщинский', '2205':'Бешенковичский', '2212':'Витебский', '2218':'Городокский', '2224':'Дубровенский', 
            '2230':'Лиозненский', '2236':'Оршанский', '2244':'Сенненский', '2246':'Толочинский', '2258':'Шумилинский', }
        self.inv_distr = {v: k for k, v in distr.items()}

        real_distrs_id=list(dict.fromkeys([line['properties']['rn'] for line in self.j['features']]))
        real_distrs_names=[distr[line] for line in real_distrs_id]
        self.dlg.comboDistr.clear()        
        self.dlg.comboDistr.addItems(real_distrs_names)
        self.change_us()
        self.dlg.comboDistr.activated.connect(self.change_us) 
        self.dlg.addvecButton.clicked.connect(self.add_vec2)        
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()        
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
    
    def change_us(self):
        distr_id=self.inv_distr[self.dlg.comboDistr.currentText()]
        usnames=['все',*[f["properties"]["usname"] for f in self.j['features']  if f['properties']['rn'] == str(distr_id)]]
        usids=[f["properties"]["usern_co"] for f in self.j['features']  if f['properties']['rn'] == str(distr_id)]
        self.usids=[usids[0][:5],*usids]        
        self.dlg.comboUsers.clear()        
        self.dlg.comboUsers.addItems(usnames)
        
    def base_map(self):
        from qgis.core import QgsRasterLayer
        rb=self.dlg.sender()
        if rb.isChecked():
            print(rb.text())
            if rb.text()=='esri':
                self.radio_esri()
            
            
            elif rb.text()=='osm':
                self.radio_osm()
            else:
                self.radio_base()
            
    def radio_esri(self):
        from qgis.core import QgsRasterLayer, QgsLayerTreeLayer
        lr_name='base_map'
        wms_url="type=xyz&url=https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D&zmax=20&zmin=0&http-header:referer="
        root_lr=QgsProject.instance().layerTreeRoot()        
        lr = [layer for layer in root_lr.children() if layer.name() == lr_name]        
        try:
                [root_lr.removeChildNode(child) for child in lr if child.name() == lr_name]
        except:
            pass
        rlayer = QgsRasterLayer(wms_url, lr_name, 'wms')
        QgsProject.instance().addMapLayer(rlayer, False)
        QgsProject.instance().layerTreeRoot().insertChildNode(-1, QgsLayerTreeLayer(rlayer))        
        self.iface.mapCanvas().refresh()
        

    def radio_osm(self):
        from qgis.core import QgsRasterLayer, QgsLayerTreeLayer
        lr_name='base_map'
        wms_url="type=xyz&url=https://tile.openstreetmap.de/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=20&zmin=0&http-header:referer="
        
        root_lr=QgsProject.instance().layerTreeRoot()        
        lr = [layer for layer in root_lr.children() if layer.name() == lr_name]        
        try:
                [root_lr.removeChildNode(child) for child in lr if child.name() == lr_name]
        except:
            pass
        rlayer = QgsRasterLayer(wms_url, lr_name, 'wms')
        QgsProject.instance().addMapLayer(rlayer, False)
        QgsProject.instance().layerTreeRoot().insertChildNode(-1, QgsLayerTreeLayer(rlayer))        
        self.iface.mapCanvas().refresh()

    
    def radio_base(self):
        from qgis.core import QgsRasterLayer, QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsLayerTreeLayer
        from qgis.PyQt.QtWidgets import (QApplication)

        lr_name='base_map'
        wms_url=f"crs=CRS:84&dpiMode=7&format=image/png&layers=pikurr:image_assessment&styles&url={self.geoserver_url}/geoserver/wms?version=1.1.0"
        
        root_lr=QgsProject.instance().layerTreeRoot()        
        lr = [layer for layer in root_lr.children() if layer.name() == lr_name]
        try:
                [root_lr.removeChildNode(child) for child in lr if child.name() == lr_name]                
        except:
            pass
        rlayer = QgsRasterLayer(wms_url, lr_name, 'wms')
        QgsProject.instance().addMapLayer(rlayer, False)
        QgsProject.instance().layerTreeRoot().insertChildNode(-1, QgsLayerTreeLayer(rlayer))        
        QApplication.instance().processEvents()
        QgsProject.instance().setCrs(QgsCoordinateReferenceSystem(3857))        
        self.iface.mapCanvas().refresh()






    def add_vec2(self):
        import requests, json
        http=f'{self.geoserver_url}/geoserver/wps'
        curids=self.dlg.comboUsers.currentIndex()

        from qgis.core import QgsRasterLayer, QgsRectangle
        lr_name='fields'
        wms_url=f"IgnoreGetMapUrl=1&crs=CRS:84&dpiMode=7&format=image/png&layers=fields&styles&url={self.geoserver_url}/geoserver/pikurr/wms?CQL_FILTER=nr_user LIKE '{self.usids[curids]}%'"
        rlayer = QgsRasterLayer(wms_url, lr_name, 'wms')
        lr = [layer.id() for layer in QgsProject.instance().mapLayers().values() if layer.name() == lr_name]
        
        def prepare_xml_query(wpsxml,filter_type,prop, value):
            possibility=['PropertyIsEqualTo','PropertyIsLike','PropertyIsNull','PropertyIsBetween','PropertyIsGreaterThan','PropertyIsGreaterThanOrEqualTo','PropertyIsLessThan','PropertyIsLessThanOrEqualTo']
            if filter_type not in possibility:
                raise Exception('filter_type must be one of {}'.format(possibility))
            
            from qgis.PyQt.QtCore import QFile
            fileh = QFile(f':/plugins/trash/{wpsxml}')
            fileh.open(QFile.ReadOnly)
            xmlbody=fileh.readAll().data().decode('utf-8')
            fileh.close()

            filter=f"""<ogc:Filter>
                            <ogc:{filter_type} wildCard="*" singleChar="." escape="!">
                                <ogc:PropertyName>{prop}</ogc:PropertyName>
                                <ogc:Literal>{value}*</ogc:Literal>
                            </ogc:{filter_type}>
                        </ogc:Filter>"""
            return xmlbody.format(filter=filter)        
        
        from qgis.core import QgsRasterLayer, QgsCoordinateTransform, QgsCoordinateReferenceSystem
        
        map_epsg= self.iface.mapCanvas().mapSettings().destinationCrs().authid()
        source_crs = QgsCoordinateReferenceSystem(rlayer.crs().authid())
        dest_crs = QgsCoordinateReferenceSystem(map_epsg)
        transform = QgsCoordinateTransform(source_crs, dest_crs, QgsProject.instance()) 
        if map_epsg != rlayer.crs().authid(): 
            source_crs = QgsCoordinateReferenceSystem(rlayer.crs().authid())
            dest_crs = QgsCoordinateReferenceSystem(map_epsg)
            transform = QgsCoordinateTransform(source_crs, dest_crs, QgsProject.instance())                
            bbox= transform.transformBoundingBox(rlayer.extent())
        else: 
            bbox=rlayer.extent()         
        
        try:
            [QgsProject.instance().removeMapLayer(l) for l in lr]
            self.iface.mapCanvas().refresh()
        except:
            pass
        # else:
        QgsProject.instance().addMapLayer(rlayer)  
        # zoom to layer
        if self.dlg.comboUsers.currentIndex()==-1:
            self.iface.mapCanvas().setExtent(bbox)         
            self.iface.mapCanvas().refresh() 
        else:
            http=f'{self.geoserver_url}/geoserver/wps'           
            wps_qr=prepare_xml_query('demowps4.xml','PropertyIsLike','nr_user',self.usids[curids])                
            r=requests.post(http, data=wps_qr, headers = {"Content-Type": "text/xml"})
            from xml.etree import ElementTree as ET 
            root = ET.fromstring(r.text)            
            # crs=root.attrib
            xy1=root[0].text.split(' ')
            xy2=root[1].text.split(' ')
            bbox=' '.join(xy1+xy2)
            bbox=[float(i.strip()) for i in bbox.split(' ')]
            bbox= transform.transformBoundingBox(QgsRectangle(*bbox))
            self.iface.mapCanvas().setExtent(bbox)
            self.iface.mapCanvas().refresh()

        wps_qr=prepare_xml_query('demowps5.xml','PropertyIsLike','nr_user',self.usids[curids])
        r=requests.post(http, data=wps_qr, headers = {"Content-Type": "text/xml"})
        jsstat=json.loads(r.text)             
        

        flds={"Count":"количество","Sum":"площадь, га"}
        jsstat["AggregationFunctions"]
        
        
        



        html=f'''<table><thead><tr>
                    <td> &nbsp;&nbsp;&nbsp;&nbsp; </td>
                    <td><b>сценарий</b></td>
                    <td><b>{flds[jsstat["AggregationFunctions"][0]]}&nbsp;&nbsp;&nbsp;&nbsp;</b></td>
                    <td><b>{flds[jsstat["AggregationFunctions"][1]]}</b></td>
                    
                    </tr>
                </thead><tbody>'''
        scenar= {'meadow':'луговое с/х','forest':'перевод в л/х','clearing': 'с/х после расчистки', 'tillage': 'пахотное с/х'}
        colors= {'meadow':'#88d9b530','forest':'#882C7D2C','clearing': '#880000CC', 'tillage': '#88b85c06' }
        
        
        sums=[sum (i) for i in list(zip(*jsstat['AggregationResults']))[1:]]
        for line in jsstat['AggregationResults']:
            type=line[0]
            html+=f'''<tr>
                        <td style="background-color:{colors[type]}"/>
                        <td>{scenar[type]}</td>
                        <td>{line[1]}  ({round(line[1]/sums[0]*100,1)}%)</td>
                        <td>{line[2]}  ({round(line[2]/sums[1]*100,1)}%)</td>
                    </tr>'''
 
        html+=f'''<tr>
                    <td> &nbsp;&nbsp;&nbsp;&nbsp; </td>
                    <td><b>ИТОГО</b></td>
                    <td><b>{round(sums[0],2)}</b></td>
                    <td><b>{round(sums[1],2)}</b></td>
                </tr>
                </tbody></table>'''
        self.dlg.textBrowser.setHtml(html)