server {
    listen 80;
    server_name _;

    # React SPA (проксируем в контейнер react-client)
    location / {
        proxy_pass http://react-client/;
        proxy_set_header Host $host;
        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }

    # GeoServer
    location /geoserver/ {
        proxy_pass http://geoserver:8080/geoserver/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
