server {
    listen 80;
    server_name www.geobotany.xyz;

    return 301 http://geobotany.xyz$request_uri;
}

server {
    listen 80;
    server_name geobotany.xyz;

    # React SPA
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # GeoServer
    location /geoserver/ {
        proxy_pass http://geoserver:8080/geoserver/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
